# Generated by Django 4.0.1 on 2022-02-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useraccounts', '0001_initial'),
        ('roomsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookhosteltable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=40)),
                ('duration', models.IntegerField()),
                ('booked', models.BooleanField(default=False)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('PAID', 'PAID'), ('DUE', 'DUE')], max_length=10)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.student')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomsapp.roommodel')),
            ],
            options={
                'db_table': 'bookhostel_table',
                'managed': True,
            },
        ),
    ]
