# Generated by Django 4.0.1 on 2022-01-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookhosteltable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=35)),
                ('emergency_no', models.IntegerField()),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_relation', models.CharField(max_length=100)),
                ('guardian_no', models.CharField(max_length=20)),
                ('guardian_address', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('seater', models.IntegerField()),
                ('food', models.CharField(max_length=20)),
                ('room_alloted', models.IntegerField()),
                ('price', models.IntegerField()),
                ('booked_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'bookhostel_table',
                'managed': True,
            },
        ),
    ]
