# Generated by Django 4.0.1 on 2022-02-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_remove_bookhosteltable_booked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookhosteltable',
            options={'managed': True, 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RenameField(
            model_name='bookhosteltable',
            old_name='uid',
            new_name='hostel_name',
        ),
    ]
