# Generated by Django 4.0.1 on 2022-02-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_alter_hostel_number_of_doublerooms_and_more'),
        ('bookingapp', '0003_alter_bookhosteltable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhosteltable',
            name='hostel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel'),
        ),
    ]
