# Generated by Django 4.0.1 on 2022-02-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='photo',
            field=models.ImageField(upload_to='hostels/'),
        ),
    ]
