# Generated by Django 4.0.1 on 2022-02-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_alter_hostel_number_of_doublerooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='number_of_doublerooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='number_of_singlerooms',
            field=models.IntegerField(default=0),
        ),
    ]
