# Generated by Django 4.0.1 on 2022-02-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student Accounts'},
        ),
    ]
