# Generated by Django 4.0.1 on 2022-01-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookhosteltable',
            old_name='seater',
            new_name='room_capacity',
        ),
    ]
