# Generated by Django 4.0.1 on 2022-02-04 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roomsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='lavatory',
            field=models.CharField(choices=[('In Room', 'In Room'), ('Outdoors', 'Outdoors')], default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommodel',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='hostels/'),
            preserve_default=False,
        ),
    ]
