# Generated by Django 4.0.1 on 2022-02-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='room_no',
            field=models.CharField(max_length=4),
        ),
    ]
