# Generated by Django 4.0.1 on 2022-02-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsapp', '0002_roommodel_lavatory_roommodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='photo',
            field=models.ImageField(upload_to='hostels_rooms/'),
        ),
    ]
